#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

# neovim
if ! hash nvim 2>/dev/null; then
  sudo add-apt-repository -y ppa:neovim-ppa/stable
  sudo apt-get update
  sudo apt-get install neovim
fi

# vundle
if ! [ -d $HOME/.vim ] && ! [ -d $HOME/.vim/bundle ]; then
  mkdir -p $HOME/.vim/bundle
  git clone https://github.com/VundleVim/Vundle.vim.git $HOME/.vim/bundle/Vundle.vim
  nvim +PluginInstall +qall
fi
