#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

# rbenv
if ! type "rbenv" > /dev/null; then
  # ubuntu dependencies
  sudo apt-get install gcc-6 autoconf bison build-essential libssl-dev libyaml-dev libreadline6-dev zlib1g-dev libncurses5-dev libffi-dev libgdbm3 libgdbm-dev

  # copy rbenv
  git clone https://github.com/rbenv/rbenv.git $HOME/.rbenv
  (cd $HOME/.rbenv && src/configure && make -C src) || true

  # ruby-build
  mkdir -p "$(rbenv root)"/plugins
  git clone https://github.com/rbenv/ruby-build.git "$(rbenv root)"/plugins/ruby-build

  # ruby-2.4.0
  rbenv install 2.4.0
fi
