#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

# x2go (see https://serverfault.com/a/700771/373240)
if [ -f /sys/hypervisor/uuid ] && [ `head -c 3 /sys/hypervisor/uuid` == ec2 ]; then
  # TODO: maybe make it work outside ubuntu in the future?

  sudo add-apt-repository -y ppa:x2go/stable
  sudo apt-get update
  sudo apt-get -y install pulseaudio x2goserver x2goserver-xsession
  sudo apt-get install --no-install-recommends ubuntu-desktop
fi
