#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

# Install Neovim.
if ! type "nvim" > /dev/null; then
  curl -L https://github.com/neovim/neovim/releases/download/v0.2.0/nvim.appimage \
       -O $HOME/bin/nvim
fi

# Install Vundle.
if ! [ -d $HOME/.vim/bundle ]; then
  mkdir -p $HOME/.vim/bundle
  git clone https://github.com/VundleVim/Vundle.vim.git $HOME/.vim/bundle/Vundle.vim
  nvim +PluginInstall +qall
fi

